# Generated by Django 3.2.9 on 2021-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211112_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_username',
            field=models.CharField(blank=True, default='', max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_username',
            field=models.CharField(blank=True, default='', max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tech',
            field=models.CharField(blank=True, default='', max_length=222, null=True),
        ),
    ]
